### ISSUE TITLE
Enable debugging for all providers in all bootstrapping mechanisms, if possible

### ISSUE THREAD

**Issue by nimakaviani** [aws-samples/crossplane-aws-blueprints#2]
We are not enabling debugging for AWS providers when deploying via terraform. This is what we have for the terraform installation:

https://github.com/aws-samples/crossplane-aws-blueprints/blob/9197d704ea8f55621aac4422bd166d6e3c44b583/bootstrap/terraform/main.tf#L186-L197

vs what we have on the AWS provider:

https://github.com/aws-samples/crossplane-aws-blueprints/blob/9197d704ea8f55621aac4422bd166d6e3c44b583/bootstrap/eksctl/crossplane/aws-provider.yaml#L20-L24

Also, do we have the possibility to enable debugging for the jet provider as well. if so, we need to do it:

https://github.com/aws-samples/crossplane-aws-blueprints/blob/9197d704ea8f55621aac4422bd166d6e3c44b583/bootstrap/eksctl/crossplane/jet-aws-provider.yaml#L20-L22

**Comment by vara-bonthu** [comment]
PR merged. Closing this issue
