### ISSUE TITLE
[FEATURE] Use subnetIdSelector.matchLabels for subnet selection in EKS composition

### ISSUE THREAD

**Issue by MichaelVL** [aws-samples/crossplane-aws-blueprints#32]
#### Is your feature request related to a problem? Please describe
The EKS cluster composition in `compositions/aws-provider/eks` require manual specification of subnet Ids. In Kubernetes, labels are typically used to reference resources, i.e. labelling subnets and using the `resourcesVpcConfig.subnetIdSelector.matchLabels` feature  of the `cluster.eks.crossplane.io` resource would be more convenient and less error prone. Prior art for this can be found in https://github.com/upbound/platform-ref-aws

#### Describe the solution you'd like
A working example can be found here: https://github.com/MichaelVL/crossplane-aws-blueprints/tree/feature/subnet-label-selector

This working example implements the following

- Adds a new parameter `networkId` to the `xvpcsubnets` composition, which is propated to the subnet label `network.awsblueprints.io/network-id`. The idea behind NOT using the VPC name is that this is a logical network name and may consist of more than a VPC. The label use dash-case as is common for Kubernetes labels.
- Similarly adds a `networkId` to the `xamazoneks` composition and which is used for subnet selection in the cluster `resourcesVpcConfig` settings and similarly for the node group.
- Updates example claims with the `networkId` parameter.

I will be happy to make a PR from this working example.

#### Describe alternatives you've considered
None

#### Additional context
The 'working example' was heavily inspired by https://github.com/upbound/platform-ref-aws

**Comment by haarchri** [comment]
@nabuskey think this issue is already fixed 

https://github.com/aws-samples/crossplane-aws-blueprints/blob/main/examples/aws-provider/composite-resources/vpc-subnets-eks/vpc-subnets-eks-claims.yaml

**Comment by nabuskey** [comment]
@haarchri Thanks!
